### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#10]
## Value proposition

As a user,
I want to navigate to the homepage and the blog page
so that I can have an overview on what's new and important on the page

#### Hamburger Menu (Home Page)

<img width="300" alt="Screenshot 2022-07-29 at 12 29 43" src="https://user-images.githubusercontent.com/99472170/181741255-06b6d2ae-e600-4a0c-8a4b-e8773434df52.png">

#### Navigation Page

<img width="300" alt="Screenshot 2022-07-29 at 12 27 02" src="https://user-images.githubusercontent.com/99472170/181741440-52becbc5-6382-4f5c-987e-018241649b3b.png">

## Acceptance criteria

- [ ] Navigation slides up on click/tap on "Hamburger" button
- [ ] Navigation closes (and slides down) on click/tap on close button
- [ ] User can navigate to Blog and Home page

## Complexity

Small | Medium | **Large**

## Tasks

- [ ] Create branch nav-dev
- [ ] Create Navigation Page
- [ ] Implement React Router
- [ ] Add routes for home page, blog and navigation
- [ ] CSS page to page animation (up and down slides
- [ ] Hamburger Menu, close button
- [ ] CSS Background SVGs
- [ ] Storybook
- [ ] Tests

**Comment by actyvystom** [comment]
Also a good one! 👍🏻
Just one question: which components will be used for Storybook?

**Comment by SLS-BLN** [comment]
Every component.
