### ISSUE TITLE
Search by tag Button

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#15]
## Value proposition

As a user,
I want to click on a tag button
so that I can get more videos or blog posts on that issue.

## Description

When pressing the tab button, the user sees a list of blog posts and videos on a new page.
On this page there are more tags - so the user can switch to another issue of interest.

## Acceptance criteria

- [ ] when the user presses the tag button a list of blog posts and videos is shown
- [ ] when the user presses on another tag button, another list of blogs post and videos ist shown
- [ ] the tag button needs further information for users of screen readers - the tag itself is not enough to understand what will happen on pressing the button
- [ ] back button - user is redirected to the page before

## Complexity

Small | Medium | **Large**

## Tasks

- [ ] Create branch search-by-tag
- [ ] add Aria Label to tag button - tag button is already in use
- [ ] add navigate hook to tag button / useSearchParam
- [ ] create a nested route (url/search?tag-name) - React Router 
- [ ] add Search folder
- [ ] add SearchByTag.js file
- [ ] create SearchByTag component with 
- - [ ] filter on video and blog data arrays
- - [ ] list of other tags / map function

**Comment by PReichetanz** [comment]
Hi Stefan, 

nice story!
Two questions:
Why are the tags "Audio", "Schnitt" and "Kamera" displayed three times? And why has the smaller tag "Audio" above the blog post another color than the search tag? I think this might be confusing for the user.
