### ISSUE TITLE
Search & Results Page

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#16]
## Value proposition

As a user,
I want to search the whole page
so that I can find the information I need.

## Description

<img width="320" alt="Screenshot 2022-08-10 at 08 38 20" src="https://user-images.githubusercontent.com/99472170/183832344-fecf4c8f-a5a2-47d2-9bc1-237183a0723a.png">
<img width="320 alt="Screenshot 2022-08-10 at 08 40 15" src="https://user-images.githubusercontent.com/99472170/183832639-905bf9e6-b440-43e6-b6f6-1d39d9829e0d.png">

## Acceptance criteria

- [ ] Input field for text search
- [ ] search by tag (click on button)
- [ ] search results are displayed with a short description
- [ ] back button

## Complexity

Small | Medium | **Large**

## Tasks

- [ ] Create branch search
- [ ] add search page (routes)
- [ ] add search results page (nested route)
- [ ] search form (onChange, onSubmit handlers)
- [ ] filter function (videoEntries and blogEntries data)
- [ ] component Result (Headline, 2 lines of description)
- [ ] back button - SVG instead of text (new component)
- [ ] hide search by tag if search form is active

**Comment by PReichetanz** [comment]
Hi Stephan,

looks good!

A few questions:
- How do I get to this search page, via the menu or somehow else? Is the arrow in the right lower corner the back button? Why is it missing on the second wireframe?
- I am confused from the tags "Audio", "Schnitt" and "Kamera" displayed three times; I guess you mean different tag names in line two and three? Let's use real-world tags ;) 
- What happens if I choose one of the search results via keyboard + enter: Does the search starts immediately or do I have to click the search button afterwards?
- What is exactly displayed when the search is done?
- What happens if I enter a keyword for which there is no result?

**Comment by SLS-BLN** [comment]
Hi Paul - thanks for your feedback. It is really very helpful. I hope everything is easier to understand now. The design was a bit outdated. The search results page by keyword is already in use (see my latest PR). I plan to reuse some of the components. The back button (the blue one on the last image) could replace the SVG on the first image. This is a question of UX - I like the SVG better, but the blue button is already used everywhere. 
Best
Stefan
