### ISSUE TITLE
Blog post component

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#3]
**I need** to see the most important content of the blog
**to be able to** decide quickly if it useful for me

**As a** user
**I need** a blog post  
**to be able** to read it
 
## Description
 
<img width="400" alt="Screenshot 2022-07-18 at 10 15 36" src="https://user-images.githubusercontent.com/99472170/179474218-69a77f57-5f08-4081-af14-133a2f1f9190.png">

## Acceptance Criteria

- [ ] Headline
- [ ] Leadtext
- [ ] Text
- [ ] Subheadings
- [ ] scrollable
- [ ] background color, font sizes should look good on smartphone

## Tasks

(for developers team)

- [ ] implement nanoid (npm)
- [ ] create data structure with ID, headline, leadtext, text, subheading
- [ ] create component folder blog
- [ ] add file blog.js
- [ ] create article object - only one with content
- [ ] storybook
- [ ] decide between styled components, CSS Modules and plain CSS
- [ ] add styling - global, blog (bg-color, fonts etc.)
- [ ] test layout with figma App (prototype is already working)
- [ ] double check contrast (aa aria rating - or better)
- [ ] write test
