### ISSUE TITLE
Prototype on Figma

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#5]
## Value proposition

Paula as a member of the marketing team
wants to read articles and watch videos on the blog
so that she is informed and learns something she can apply to her work

## Description

UI and UX should help Paula to reach her goals.
It should be clear where to click when she ...

	- wants to find something
	- wants to read the newest blog posts
	- wants to watch the newest videos

Link to Project in Figma 
[Marketing mit Video](https://www.figma.com/file/ph3tBtIictykhXVtUF4PVV/Video-Marketing?node-id=1%3A7)

<img width="420" alt="Screenshot 2022-07-22 at 10 54 40" src="https://user-images.githubusercontent.com/99472170/180402854-ac3e907d-954b-4715-b16d-42cf11d9888c.png">

	

## Acceptance criteria

- [ ] Figma Prototype ready for user testing
- [ ] Feedback from at least 1 designer
- [ ] Feedback from at least 3 users

## Complexity

Small | **_Medium_** | Large

## Tasks

- [ ] research how make content scrollable / Figma Docs, Udemy Course
- [ ] test Figma prototype on at least 2 different devices / install Figma App on 2nd phone
- [ ] post on Slack / ask coaches which channel is right
- [ ] Slack DM to design coach Sascha Lerner - ask for feedback
- [ ] mail to family & friends - ask for feedback

**Comment by PReichetanz** [comment]
Hi Stefan,

I like this user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Value Proposition
- I don't really see why you need Paula **as a member of the marketing team** here, because the content of the blog articles may refer to marketing, but the development goal is to be able to read blog posts (and it doesn't matter what content they will have).

## Description
I guess the displayed wireframes are only examples of the entire Figma prototype? Then it should be fine that it's not clear how both frames relate to each other. 

## Acceptance Criteria
- The first criteria is not correct here: This must be finished **before** the user story starts, it thus cannot be a critera at the of the story as well.
- By now, the story will be finished as soon as you have one feedback from a designer and three from users, regardless whether it is positive or negative. If you need also a specific amount of approving feedback, state this here.

## Tasks
- If you want feedback for your design / Figma prototype in particular, you can use the #design Slack channel.

**Comment by SLS-BLN** [comment]
Hey Paul, thank you for your detailed feedback. I really appreciate. The changes have already been implemented. Many thanks.
