### ISSUE TITLE
List of blog posts

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#8]
## Value proposition

As a user,
I want to scroll through a list of Blog posts
so that I can decide which one I want to read next.

## Description

<img width="300" alt="Screenshot 2022-07-29 at 11 50 55" src="https://user-images.githubusercontent.com/99472170/181733880-f9de1cbe-934f-4953-8cb5-fba863c2c2a6.png">

## Acceptance criteria

- [ ] each Blog post is displayed in a card
- [ ] each card contains a tag, an image, a heading and a short text
- [ ] back to start button at the end of the list

## Complexity

Small | **Medium** | Large

## Tasks

- [ ] Create branch overview-dev
- [ ] Create card component with mapping function
- [ ] [Apply an ellipsis to multiline text
- [ ] button back to start

**Comment by actyvystom** [comment]
A nice one! 👍🏻 
Just one remark: For your second task I guess you mean "mapping through the list of blog posts and render each post with a card component..."?
