### ISSUE TITLE
Homepage with carousel

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/Capstone-Project#9]
## Value proposition

As a user,
I want to start my journey on the blog with an overview of the newest content
so that I can decide which blog post I want to read.

## Description

<img width="300" alt="Screenshot 2022-07-29 at 12 07 14" src="https://user-images.githubusercontent.com/99472170/181737894-803e53aa-6d32-461a-ae6e-bb680830c522.png">

## Acceptance criteria

- [ ] the newest blog post is presented at the top - with a big image, heading and lead text
- [ ] more blog post are presented in a scrollable carousel
- [ ] if the user clicks on any of the blog post or images she is directed to the blog post itself

## Complexity

Small | Medium | **Large**

## Tasks

- [ ] Create branch home-dev
- [ ] Add hero section with image, heading, lead / mapping fn
- [ ] Create Carousel / fill it with components from the blog list - should be reusable without any hassles

**Comment by actyvystom** [comment]
Looks good! 👍🏻
